# Generated by Django 5.2.7 on 2025-10-29 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DOI', models.CharField(max_length=100)),
                ('Link', models.TextField()),
                ('Source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ORCID', models.TextField()),
                ('Username', models.TextField()),
                ('FormalName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research', models.ForeignKey(db_column='ResearchId', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.research')),
                ('Researcher', models.ForeignKey(db_column='ResearcherId', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearcherResearch',
                'indexes': [models.Index(fields=['Researcher', 'Research'], name='ResearcherR_Researc_bd9725_idx')],
                'unique_together': {('Researcher', 'Research')},
            },
        ),
    ]
