# Generated by Django 5.2.7 on 2025-12-03 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DOI', models.CharField(blank=True, max_length=100, null=True)),
                ('Link', models.TextField()),
                ('title', models.TextField()),
                ('Source', models.TextField()),
                ('pubYear', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('noOfCititations', models.IntegerField(default=0)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Researches',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('nationalNumber', models.CharField(default='0', max_length=15, primary_key=True, serialize=False)),
                ('ORCID', models.TextField()),
                ('scholarProfileLink', models.TextField()),
                ('academicName', models.TextField(blank=True, null=True)),
                ('scholarProfileImageURL', models.TextField(blank=True, null=True)),
                ('organisationalDomain', models.TextField(blank=True, null=True)),
                ('jobTitle', models.TextField()),
                ('organisationId', models.DecimalField(decimal_places=0, max_digits=30)),
                ('totalNumberOfCitiations', models.IntegerField(default=0)),
                ('numberOfCitiationsInLastFiveYears', models.IntegerField(default=0)),
                ('hindex', models.IntegerField(default=0)),
                ('hindexInLastFiveYears', models.IntegerField(default=0)),
                ('i10index', models.IntegerField(default=0)),
                ('i10index5y', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Researchers',
            },
        ),
        migrations.CreateModel(
            name='ResearcherCites',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('noOfCitations', models.IntegerField()),
                ('researcher', models.ForeignKey(db_column='researcherNationalNumber', on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearchersCites',
                'constraints': [models.UniqueConstraint(fields=('Id', 'researcher'), name='unique_id_researcher')],
            },
        ),
        migrations.CreateModel(
            name='ResearcherInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('researcher', models.ForeignKey(db_column='researcherNationalNumber', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearchersInterests',
                'constraints': [models.UniqueConstraint(fields=('id', 'researcher'), name='unique_researcher')],
            },
        ),
        migrations.CreateModel(
            name='ResearcherResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research', models.ForeignKey(db_column='ResearchId', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.research')),
                ('Researcher', models.ForeignKey(db_column='nationalNumber', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearcherResearch',
                'indexes': [models.Index(fields=['Researcher', 'Research'], name='ResearcherR_nationa_fd38d0_idx')],
                'unique_together': {('Researcher', 'Research')},
            },
        ),
    ]
