# Generated by Django 5.2.7 on 2025-12-04 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchContributions',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memberOrcid', models.TextField(blank=True, null=True)),
                ('memberPositionInSearch', models.TextField()),
                ('memberAcademicName', models.TextField()),
                ('research', models.ForeignKey(db_column='researcherId', on_delete=django.db.models.deletion.CASCADE, related_name='researchContributions', to='WebScraping.research')),
                ('researcher', models.ForeignKey(db_column='researcherNationalNumber', on_delete=django.db.models.deletion.CASCADE, related_name='researcherContributions', to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearchContributions',
                'constraints': [models.UniqueConstraint(fields=('research', 'researcher'), name='Researcher_Contribution')],
            },
        ),
    ]
