# Generated by Django 5.2.7 on 2025-11-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0002_research_created_at_research_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='DOI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
