# Generated by Django 5.2.7 on 2025-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0002_researchcontributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='pubDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
