# Generated by Django 5.2.7 on 2025-12-04 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0003_research_pubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchIndex',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.TextField(blank=True, null=True)),
                ('research', models.ForeignKey(db_column='researcherId', on_delete=django.db.models.deletion.CASCADE, related_name='researchIndex', to='WebScraping.research')),
                ('researcher', models.ForeignKey(db_column='researcherNationalNumber', on_delete=django.db.models.deletion.CASCADE, related_name='researcherIndex', to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearchIndexes',
                'constraints': [models.UniqueConstraint(fields=('research', 'researcher'), name='Researcher_Indexes')],
            },
        ),
    ]
