# Generated by Django 5.2.7 on 2025-12-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0004_researchindex'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchindex',
            name='Researcher_Indexes',
        ),
        migrations.AddConstraint(
            model_name='researchindex',
            constraint=models.UniqueConstraint(fields=('researcher',), name='Researcher_Indexes'),
        ),
    ]
