# Generated by Django 5.2.7 on 2025-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0005_remove_researchindex_researcher_indexes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchindex',
            name='Researcher_Indexes',
        ),
        migrations.AddConstraint(
            model_name='researchindex',
            constraint=models.UniqueConstraint(fields=('researcher', 'Id'), name='Researcher_Indexes'),
        ),
    ]
