# Generated by Django 5.2.7 on 2025-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0006_remove_researchindex_researcher_indexes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchcontributions',
            name='Researcher_Contribution',
        ),
        migrations.AddConstraint(
            model_name='researchcontributions',
            constraint=models.UniqueConstraint(fields=('research', 'Id'), name='Researcher_Contribution'),
        ),
    ]
