# Generated by Django 5.2.7 on 2026-02-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0007_remove_researchcontributions_researcher_contribution_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchcontributions',
            name='Researcher_Contribution',
        ),
        migrations.AddField(
            model_name='research',
            name='magazine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchcontributions',
            name='memberPositionInSearch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchcontributions',
            name='research',
            field=models.ForeignKey(db_column='researchId', on_delete=django.db.models.deletion.CASCADE, related_name='researchContributions', to='WebScraping.research'),
        ),
        migrations.AddConstraint(
            model_name='researchcontributions',
            constraint=models.UniqueConstraint(fields=('research', 'Id'), name='Research_Contribution'),
        ),
    ]
