# Generated by Django 5.2.7 on 2026-02-01 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0008_remove_researchcontributions_researcher_contribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCites',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('numberOfCites', models.IntegerField()),
                ('research', models.ForeignKey(db_column='researchId', on_delete=django.db.models.deletion.CASCADE, related_name='researchCites', to='WebScraping.research')),
            ],
            options={
                'db_table': 'ResearchCites',
                'constraints': [models.UniqueConstraint(fields=('research', 'Id'), name='Research_Cites')],
            },
        ),
    ]
