# Generated by Django 5.2.7 on 2026-02-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0009_researchcites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='magazine',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='research',
            name='journal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='noOfPages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='pubURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='relatedResearchURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='volume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
