# Generated by Django 5.2.7 on 2026-02-02 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0010_rename_magazine_research_abstract_research_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'Interests',
            },
        ),
        migrations.RemoveConstraint(
            model_name='researcherinterest',
            name='unique_researcher',
        ),
        migrations.RemoveField(
            model_name='research',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='researcherinterest',
            name='name',
        ),
        migrations.AlterField(
            model_name='researcherinterest',
            name='researcher',
            field=models.ForeignKey(db_column='researcherNationalNumber', on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to='WebScraping.researcher'),
        ),
        migrations.AddField(
            model_name='researcherinterest',
            name='interest',
            field=models.ForeignKey(blank=True, db_column='interestId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='WebScraping.interest'),
        ),
        migrations.AddConstraint(
            model_name='researcherinterest',
            constraint=models.UniqueConstraint(fields=('interest', 'researcher'), name='unique_researcher_interest'),
        ),
    ]
