# Generated by Django 5.2.7 on 2026-02-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0011_interest_remove_researcherinterest_unique_researcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcontributions',
            name='memberScholarProfileURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
