# Generated by Django 5.2.7 on 2026-03-04 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0012_researchcontributions_memberscholarprofileurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scholarProfileLink', models.TextField()),
                ('academicName', models.TextField(blank=True, null=True)),
                ('scholarProfileImageURL', models.TextField(blank=True, null=True)),
                ('jobTitle', models.TextField()),
            ],
            options={
                'db_table': 'CoAuthors',
            },
        ),
        migrations.CreateModel(
            name='ResearcherCoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoAuthor', models.ForeignKey(db_column='CoAuthorId', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.coauthor')),
                ('Researcher', models.ForeignKey(db_column='nationalNumber', on_delete=django.db.models.deletion.CASCADE, to='WebScraping.researcher')),
            ],
            options={
                'db_table': 'ResearcherCoAuthors',
                'indexes': [models.Index(fields=['Researcher', 'CoAuthor'], name='ResearcherC_nationa_c99652_idx')],
                'unique_together': {('Researcher', 'CoAuthor')},
            },
        ),
    ]
