# Generated by Django 5.2.7 on 2026-03-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0013_coauthor_researchercoauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='pubYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='ORCID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
