# Generated by Django 5.2.7 on 2026-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraping', '0014_alter_research_pubyear_alter_researcher_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='Source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchcontributions',
            name='memberAcademicName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='jobTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='organisationId',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='scholarProfileLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
